### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by random-fly** [BernwardWeigand/UnityUIToolkitXRAdapter#2]
Hi, its cool project!

It greats work in editor. But i cant build demo scene to PC.

Assets\Scripts\UIToolkitXRAdapter\XRAdapter\InputSystenEventSystemPatcher.cs(10,6): error CS0246: The type or namespace name 'InitializeOnLoadAttribute' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\UIToolkitXRAdapter\XRAdapter\InputSystenEventSystemPatcher.cs(10,6): error CS0246: The type or namespace name 'InitializeOnLoad' could not be found (are you missing a using directive or an assembly reference?)

If put InputSystenEventSystemPatcher to Editor folder and change field CurrentlyFocusedPanel to public, it builds properly. But nothing happens in runtime, UI button is not pressed.

Unity 2021.1.6f1

PS Sorry for bad english.

**Comment by BernwardWeigand** [comment]
Hi :)
Sorry for the delayed response😅 and thanks for the feedback. I had my notifications turned off, but now I receive them again...

I pushed a fix to the master, which works on my machine. I would be happy, if you test it on your machine.

This is an academic project, so I wrote a report about it. I will add the report as a documentation soon, this may also help to improve the understanding of the project.

Cheers,

Bernward
